### ISSUE TITLE
Did not verify the id existence when trying to delete a task

### ISSUE THREAD

**Issue by xyf7** [haowen737/pada#2]
║ 3  │ [!]the moe │ ·done  │ 18/03/30 11:03 ║
1 rows total, rendered in 169ms

➜  pada del 2
? Delete task 2 from database? Yes
deleting task id 2...
task deleted!

//there is actually no task 2

**Comment by haowen737** [comment]
@y-xiang PR is welcome to fix this

**Comment by haowen737** [comment]
Once #4 is done, this issue shoud be resolved, reopen it for issue tracing.

**Comment by xyf7** [comment]
could you please move me out :smile:  I have no idea why this repo is in my personal profile
